
[
    // Vanilla
    item('contenttweaker:lumber_vanilla_oak'),
    item('contenttweaker:lumber_vanilla_spruce'),
    item('contenttweaker:lumber_vanilla_birch'),
    item('contenttweaker:lumber_vanilla_jungle'),
    item('contenttweaker:lumber_vanilla_acacia'),
    item('contenttweaker:lumber_vanilla_dark_oak'),
    // Biomes O Plenty
    item('contenttweaker:lumber_sacred_oak'),
    item('contenttweaker:lumber_cherry'),
    item('contenttweaker:lumber_umbran'),
    item('contenttweaker:lumber_fir'),
    item('contenttweaker:lumber_ethereal'),
    item('contenttweaker:lumber_magic'),
    item('contenttweaker:lumber_mangrove'),
    item('contenttweaker:lumber_palm'),
    item('contenttweaker:lumber_redwood'),
    item('contenttweaker:lumber_willow'),
    item('contenttweaker:lumber_pine'),
    item('contenttweaker:lumber_hellbark'),
    item('contenttweaker:lumber_jacaranda'),
    item('contenttweaker:lumber_mahogany'),
    item('contenttweaker:lumber_ebony'),
    item('contenttweaker:lumber_eucalyptus'),
    // Rustic
    item('contenttweaker:lumber_planks_olive'),
    item('contenttweaker:lumber_planks_ironwood'),
    // Forestry
    item('contenttweaker:lumber_planks.larch'),
    item('contenttweaker:lumber_planks.teak'),
    item('contenttweaker:lumber_planks.acacia'),
    item('contenttweaker:lumber_planks.lime'),
    item('contenttweaker:lumber_planks.chestnut'),
    item('contenttweaker:lumber_planks.wenge'),
    item('contenttweaker:lumber_planks.baobab'),
    item('contenttweaker:lumber_planks.sequoia'),
    item('contenttweaker:lumber_planks.kapok'),
    item('contenttweaker:lumber_planks.ebony'),
    item('contenttweaker:lumber_planks.mahogany'),
    item('contenttweaker:lumber_planks.balsa'),
    item('contenttweaker:lumber_planks.willow'),
    item('contenttweaker:lumber_planks.walnut'),
    item('contenttweaker:lumber_planks.greenheart'),
    item('contenttweaker:lumber_planks.cherry'),
    item('contenttweaker:lumber_planks.mahoe'),
    item('contenttweaker:lumber_planks.poplar'),
    item('contenttweaker:lumber_planks.palm'),
    item('contenttweaker:lumber_planks.papaya'),
    item('contenttweaker:lumber_planks.pine'),
    item('contenttweaker:lumber_planks.plum'),
    item('contenttweaker:lumber_planks.maple'),
    item('contenttweaker:lumber_planks.citrus'),
    item('contenttweaker:lumber_planks.giganteum'),
    item('contenttweaker:lumber_planks.ipe'),
    item('contenttweaker:lumber_planks.padauk'),
    item('contenttweaker:lumber_planks.cocobolo'),
    item('contenttweaker:lumber_planks.zebrawood'),
    // Cuisine
    item('contenttweaker:cuisine_citrus_lumber'),
    // Rustic Painted Wood
    item('contenttweaker:painted_wood_white_lumber'),
    item('contenttweaker:painted_wood_orange_lumber'),
    item('contenttweaker:painted_wood_magenta_lumber'),
    item('contenttweaker:painted_wood_light_blue_lumber'),
    item('contenttweaker:painted_wood_yellow_lumber'),
    item('contenttweaker:painted_wood_lime_lumber'),
    item('contenttweaker:painted_wood_pink_lumber'),
    item('contenttweaker:painted_wood_gray_lumber'),
    item('contenttweaker:painted_wood_silver_lumber'),
    item('contenttweaker:painted_wood_cyan_lumber'),
    item('contenttweaker:painted_wood_purple_lumber'),
    item('contenttweaker:painted_wood_blue_lumber'),
    item('contenttweaker:painted_wood_brown_lumber'),
    item('contenttweaker:painted_wood_green_lumber'),
    item('contenttweaker:painted_wood_red_lumber'),
    item('contenttweaker:painted_wood_black_lumber'),
    // Immersive Engineering
    item('contenttweaker:treated_wood_lumber'),
    // Pyrotech
    item('contenttweaker:tarred_lumber'),
].each {
    ore('lumber').add(it)
}
