name: "Bug Report"
description: Create a new ticket for a bug.
body:
  - type: textarea
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue.
      placeholder: Short and explicit description of your incident...
      description: |
        ### The issue
        <!--- Description of the issue. --->
      
        ### To reproduce
        <!--- The steps to reproduce the issue. --->
        
        ### Screenshots
        <!--- If applicable, add screenshots to help explain your problem. --->
    validations:
      required: true
  - type: input
    attributes:
      label: "The latest.log file"
      description: |
        Please provide a [mclo.gs](https://mclo.gs/) or [gist](https://gist.github.com/) link here. (Make sure that it isn't set to expire!)
    validations:
      required: true
  - type: input
    attributes:
      label: "Underdog version"
      description: |
        What version of Underdog are you using? **Please** do not just say "latest."
    validations:
      required: true
  - type: dropdown
    attributes:
      label: "Launcher"
      description: What launcher are you using?
      multiple: true
      options:
        - CurseForge
        - MultiMC
        - PolyMC
        - GDLauncher
        - ATLauncher
        - Vanilla
    validations:
      required: true
  - type: dropdown
    attributes:
      label: "OS"
      description: What is the impacted environment?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: true
