name: "Bug Report"
description: Create a new ticket for a bug.
body:
  - type: textarea
    attributes:
      label: "Description"
      description: |
        Please enter an explicit __description__ of your issue.
        You can also add __reproduction steps__ and __screenshots__ to the description.
      placeholder: |
        Short and explicit description of your incident...
        How do you trigger this bug? Please walk us through it step by step.
        If applicable, add screenshots to help explain your problem.
    validations:
      required: true
  - type: input
    attributes:
      label: "The latest.log file"
      description: |
        Please provide a [mclo.gs](https://mclo.gs/) or [gist](https://gist.github.com/) link here. (Make sure that it isn't set to expire!)
    validations:
      required: true
  - type: input
    attributes:
      label: "Underdog version"
      description: |
        What version of Underdog are you using? Do not just say "latest" please.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: "Launcher"
      description: What launcher are you using?
      multiple: true
      options:
        - CurseForge
        - MultiMC
        - PolyMC
        - GDLauncher
        - ATLauncher
        - Vanilla
    validations:
      required: true
  - type: dropdown
    attributes:
      label: "OS"
      description: What is the impacted environment?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: true
