name: Test
run-name: "Test #${{ github.run_number }}"

on: workflow_dispatch

jobs:
  close-fixed-issues:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: close-fixed-in-dev
      uses: juraj-hrivnak/close-issues-based-on-label@master
      env:
        LABEL: "fixed in dev"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
